/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class club_pineclone_jni_demo_IntSub */

#ifndef _Included_club_pineclone_jni_demo_IntSub
#define _Included_club_pineclone_jni_demo_IntSub
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     club_pineclone_jni_demo_IntSub
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_club_pineclone_jni_demo_IntSub_sub
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
