/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class club_pineclone_jni_demo_IntMultiple */

#ifndef _Included_club_pineclone_jni_demo_IntMultiple
#define _Included_club_pineclone_jni_demo_IntMultiple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     club_pineclone_jni_demo_IntMultiple
 * Method:    registerNatives
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_club_pineclone_jni_demo_IntMultiple_registerNatives
  (JNIEnv *, jclass);

/*
 * Class:     club_pineclone_jni_demo_IntMultiple
 * Method:    multiple
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_club_pineclone_jni_demo_IntMultiple_multiple
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
