/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class club_pineclone_jni_demo_IntSum */

#ifndef _Included_club_pineclone_jni_demo_IntSum
#define _Included_club_pineclone_jni_demo_IntSum
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     club_pineclone_jni_demo_IntSum
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_club_pineclone_jni_demo_IntSum_sum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
